"""init schema

Revision ID: c9cae7be7e10
Revises: 
Create Date: 2026-08-23 19:12:57.748623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9cae7be7e10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negocios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=False),
    sa.Column('modulos_activos', sa.JSON(), nullable=False),
    sa.Column('plan_estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_ultimo_pago', sa.Date(), nullable=True),
    sa.Column('link_sunat', sa.String(length=255), nullable=True),
    sa.Column('modulo_rus_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas_descartadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=False),
    sa.Column('fecha_descarte', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cierres_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('total_bruto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_capital', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_ganancia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_efectivo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_digital', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes_vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('marca_vehiculo', sa.String(length=100), nullable=True),
    sa.Column('modelo_vehiculo', sa.String(length=100), nullable=True),
    sa.Column('tipo_aceite', sa.String(length=100), nullable=True),
    sa.Column('intervalo_meses', sa.Integer(), nullable=True),
    sa.Column('fecha_ultimo_servicio', sa.Date(), nullable=True),
    sa.Column('fecha_proximo_mantenimiento', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cola_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_sincronizado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('medida', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('estado_uso', sa.String(length=50), nullable=True),
    sa.Column('precio_lista', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('clasificacion', sa.String(length=100), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cliente_vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('precio_lista', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_vehiculo_id'], ['clientes_vehiculos.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones_wsp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['cliente_vehiculo_id'], ['clientes_vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_compra')
    op.drop_table('notificaciones_wsp')
    op.drop_table('movimientos')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('cola_sync')
    op.drop_table('clientes_vehiculos')
    op.drop_table('cierres_caja')
    op.drop_table('alertas_descartadas')
    op.drop_table('negocios')
    # ### end Alembic commands ###
