"""cola_sync: id de cliente para idempotencia de sync

Revision ID: ea7946e19e07
Revises: c9cae7be7e10
Create Date: 2026-08-23 15:14:49.904942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7946e19e07'
down_revision: Union[str, None] = 'c9cae7be7e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cola_sync', sa.Column('cliente_id', sa.String(length=64), nullable=False))
    op.create_unique_constraint('uq_cola_sync_negocio_cliente_id', 'cola_sync', ['negocio_id', 'cliente_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cola_sync_negocio_cliente_id', 'cola_sync', type_='unique')
    op.drop_column('cola_sync', 'cliente_id')
    # ### end Alembic commands ###
